version: '3'

networks:
  zeek-cluster-overlay:
    ipam:
      config:
        - subnet: 172.20.0.0/24

services:
  worker1:
    # build: zeek-ssh-node
    image: fixel/zeek-cluster:zeek-ssh-node
    networks:
      zeek-cluster-overlay:
        aliases:
          - worker1
  
  worker2:
    # build: zeek-ssh-node
    image: fixel/zeek-cluster:zeek-ssh-node
    networks:
      zeek-cluster-overlay:
        aliases:
          - worker2

  proxy:
    # build: zeek-ssh-node
    image: fixel/zeek-cluster:zeek-ssh-node
    networks:
      zeek-cluster-overlay:
        aliases:
          - proxy

  manager:
    # build: manager
    image: fixel/zeek-cluster:manager
    depends_on:
      - worker1
      - worker2
      - proxy
    # volumes:
    #  - "./path/to/your/scripts:/zeek/share/bro/site"
    networks:
      zeek-cluster-overlay:
        aliases:
          - manager

    