version: '3'

networks:
  bro-cluster-overlay:
    ipam:
      config:
        - subnet: 172.20.0.0/24

services:
  worker1:
    build: bro-ssh-node
    networks:
      bro-cluster-overlay:
        aliases:
          - worker1
  
  worker2:
    build: bro-ssh-node
    networks:
      bro-cluster-overlay:
        aliases:
          - worker2

  proxy:
    build: bro-ssh-node
    networks:
      bro-cluster-overlay:
        aliases:
          - proxy

  manager:
    build: manager
    depends_on:
      - worker1
      - worker2
      - proxy
    networks:
      bro-cluster-overlay:
        aliases:
          - manager

    